#!/bin/bash -e

# Welcome to Genexp’s laptop script! Forked from Matt Banks, forked from Thoughtbot
# Be prepared to turn your laptop (or desktop, no haters here)
# into an awesome development machine.

trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT

set -e

# Make sure we have Xcode command line tools
# xcode-select --install

# Create ~/.bin if it doesn't exist
if [[ ! -d "$HOME/.bin/" ]]; then
  mkdir "$HOME/.bin"
fi

# Create ~/Code if it doesn't exist
if [ ! -d "$HOME/Code/" ]; then
  mkdir "$HOME/Code"
fi

fancy_echo() {
  printf "\n%b\n" "$1"
}

echo "Checking for SSH key, generating one if it doesn't exist ..."
  [[ -f ~/.ssh/id_rsa.pub ]] || ssh-keygen -t rsa

if ! command -v brew &>/dev/null; then
  fancy_echo "Installing Homebrew, a good OS X package manager ..."
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
else
  fancy_echo "Homebrew already installed. Skipping ..."
fi

fancy_echo "Updating Homebrew formulas ..."
  brew update

fancy_echo "Installing homebrew packages ..."
  brew install git awscli heroku-toolbelt go python ruby node tmux

fancy_echo "Installing docker and terraform packages ..."
  brew install docker docker-compose docker-machine docker-swarm terraform

fancy_echo "Updating to latest Rubygems version ..."
  gem update --system

fancy_echo "Installing Essential NPM Packages ..."
  npm install -g eslint gulp jshint node-inspector npm-check-updates pure-prompt xo

fancy_echo "Installing Casks"
  brew cask install caskroom/fonts/font-hack caskroom/fonts/font-source-code-pro
  brew cask install qlmarkdown qlcolorcode qlstephen quicklook-json qlimagesize
  brew cask install google-chrome atom iterm2 spotify sonos 1password alfred duet slack


git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
cat << EOF > ~/.tmux.conf
# Put this at the bottom of .tmux.conf:

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'git@github.com/user/plugin'
# set -g @plugin 'git@bitbucket.com/user/plugin'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
EOF

# fancy_echo "Cloning and installing dotfiles ..."
#  git clone git@github.com:denexp/dotfiles.git ~/.dotfiles
#  cd ~/.dotfiles
#  script/bootstrap

# fancy_echo "Installing Atom packages"
#  apm stars --install

# fancy_echo "Installing Xcode color scheme"
#   cd ~/.dotfiles
#  xcode/setup
